---
# Configured in YAML cause someday soon I will only know how to write YAML...
defaultContentLanguage: "en"
languageCode: "en-us"
title: "Voltage Noir"

baseurl: "/"
theme: "terminal"
paginate: 5

# Self-own mode: On
enableEmoji: true

enableGitInfo: true
enableRobotsTXT: true

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: "blue"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 2
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: false
  # set a custom favicon (default is a `themeColor` square)
  # favicon: "favicon.ico"
  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize: false

languages:
  en:
    languageName: "English"
    title: "VN"
    subtitle: "New old garbage 2000"
    owner: "Paul Doom"
    keywords: ""
    copyright: ""
    menuMore: "Show more"
    readMore: "Read more"
    readOtherPosts: "Read other posts"

    params:
      logo:
        logoText: "VN"
        logoHomeLink: "/"

    menu:
      main:
        - identifier: "about"
          name: "About"
          url: "/about"
